version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=letters_db
