import "./globals.css"
import type { Metadata } from "next"
import { Manrope } from "next/font/google"
import { Navigation } from "@/components/Navigation"

const manrope = Manrope({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "At the moment,",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={manrope.className}>
                <header>
                    <Navigation />
                </header>
                {children}
            </body>
        </html>
    )
}
